server:
  host: "0.0.0.0"
  port: "8080"

database:
  type: "sqlite"
  filepath: "sonic.db"

log:
  level: "info"
  format: "console"

app:
  mode: "development"
  upload_dir: "./uploads"
  template_dir: "./resources/template"
  theme_dir: "./resources/template/theme"
